- name: set error status
  import_tasks: "{{ common_path }}/k8s/status.yml"
  vars:
    k8s_status_properties:
      ready: "False"
    k8s_status_conditions:
      - type: "Ready"
        status: "False"
        reason: "Error"
        message: "There was an error before completing all tasks"
