- name: pgbouncer readonly secret resource definition
  vars:
    k8s_kind: Secret
    k8s_state:
      "{{ 'absent' if postgres_mode not in ['readreplicas'] else
      pgbouncer_readonly_secret_state | default(postgres_state) }}"
    template: "{{ secret_template }}"
    metadata_name: "{{ pgbouncer_readonly_secret }}"
    secret_data: "{{ pgbouncer_readonly_secret_data }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save pgbouncer readonly secret resource definition task
  set_fact:
    k8s_pgbouncer_readonly_secret: "{{ k8s_object_task }}"
