- name: set state absent
  set_fact:
    state: absent

- name: import tasks
  block:
    - name: start terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/start.yml"

    - name: handle keydb
      import_tasks: "{{ role_path }}/tasks/state/absent/keydb.yml"

    - name: end terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/end.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
