- name: set state absent
  set_fact:
    state: absent
    k8s_wait: true

- name: import tasks
  block:
    - name: start terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/start.yml"

    - name: handle resources depending on postgres mode
      import_tasks: "{{ role_path }}/tasks/state/absent/{{ postgres_mode }}.yml"

    - name: end terminating condition
      import_tasks: "{{ common_path }}/condition/terminating/end.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
