- name: pgbouncer resource definitions
  vars:
    name: pgbouncer
    component: pgbouncer
    metadata_app: "{{ pgbouncer_readonly_appname }}"
  block:
    - import_tasks: "{{ role_path }}/tasks/resource/pgbouncer-readonly/deploy.yml"

- name: postgres readreplicas resource definitions
  vars:
    name: readreplicas
    component: readreplicas
    metadata_app: "{{ postgres_readreplicas_appname }}"
  block:
    - import_tasks: "{{ role_path }}/tasks/resource/readreplicas/sts.yml"

    - import_tasks: "{{ common_path }}/cleanup-resources.yml"
      vars:
        cleanup_label_selector: "app={{ metadata_app }}"
        cleanup_kind_list:
          - PersistentVolumeClaim

- name: pgbouncer resource definitions
  vars:
    name: pgbouncer
    component: pgbouncer
    metadata_app: "{{ pgbouncer_appname }}"
  block:
    - import_tasks: "{{ role_path }}/tasks/resource/pgbouncer/deploy.yml"

- name: postgres resource definitions
  vars:
    name: postgres
    component: postgres
    metadata_app: "{{ postgres_appname }}"
  block:
    - import_tasks: "{{ role_path }}/tasks/resource/postgres/sts.yml"

    - import_tasks: "{{ common_path }}/cleanup-resources.yml"
      vars:
        cleanup_label_selector: "app={{ metadata_app }}"
        cleanup_kind_list:
          - PersistentVolumeClaim
