- name: set state absent
  set_fact:
    state: absent

- name: import tasks
  block:
    - name: handle graphql-engine removal
      import_tasks: graphql-engine.yml

    - name: handle postgres removal
      import_tasks: postgres.yml
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
