- name: set successful status
  import_tasks: "{{ common_path }}/routine/status.yml"
  vars:
    routine_status_cr_notify_force: true
    _routine_k8s_status_properties:
      ready: "False"
      state: IngressOnly
    routine_k8s_status_properties:
      "{{ _routine_k8s_status_properties | combine({'observedGeneration': cr_status_generation | int}) }}"
    routine_k8s_status_conditions:
      - type: "Ready"
        status: "False"
        reason: "IngressOnly"
        message: "Only ingress tasks"

# to trigger reconciliation in parent CR, watchDependentResources=true is required
- name: add observed generation annotation
  vars:
    add_annotations: "{{ { cr_group + '/observedGeneration':  cr_status_generation } }}"
  import_tasks: "{{ common_path }}/add-annotations.yml"
