- name: (nfs) ganesha server config map resource definition
  vars:
    k8s_kind: ConfigMap
    k8s_state: "{{ ganesha_cm_state | default(ganesha_state) }}"
    template: "{{ cm_template }}"
    metadata_name: "{{ ganesha_cm }}"
    cm_data: "{{ ganesha_cm_data }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save (nfs) ganesha server config map resource definition task
  set_fact:
    k8s_ganesha_cm: "{{ k8s_object_task }}"
