- name: (nfs) ganesha server service resource definition
  vars:
    k8s_kind: Service
    k8s_state: "{{ ganesha_service_state | default(ganesha_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ ganesha_service }}"
    service_spec: "{{ ganesha_service_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save (nfs) ganesha server service resource definition task
  set_fact:
    k8s_ganesha_service: "{{ k8s_object_task }}"
