# THIS FILES IS SHARED BETWEEN MOODLE.M4E AND NGINX.M4E CRD

# moodle nginx envvars
moodle_nginx_envvar_fastcgi_pass:
  name: NGINX_FASTCGI_PASS
  value: "{{ php_fpm_appname }}-service:{{ php_fpm_port }}"
moodle_nginx_envvar_moodle_check_host:
  name: MOODLE_CHECK_HOST
  value: "{{ moodle_host + ( ':' + moodle_port | string if moodle_port else '' ) }}"
moodle_nginx_envvar_moodle_check_path:
  name: MOODLE_CHECK_PATH
  value: "{{ moodle_healthcheck_path }}"
moodle_nginx_envvars_base: "{{ [moodle_nginx_envvar_fastcgi_pass] +
  [moodle_nginx_envvar_moodle_check_host] + [moodle_nginx_envvar_moodle_check_path] }}"
moodle_nginx_envvars_extra: []

# moodle nginx volumes
moodle_nginx_volume_moodledata: "{{ moodle_volume_moodledata }}"
moodle_nginx_volumes_base: "{{ [moodle_nginx_volume_moodledata] }}"
moodle_nginx_volumes_extra: []

# nginx
nginx_appname: "{{ meta_name }}-nginx"
nginx_inventory_uuid: "{{ (cr_group + cr_version + cr_kind + meta_namespace + meta_name) | to_uuid }}"

# nginx deploy
# nginx_size: 1
nginx_image: "{{ moodle_image }}"
nginx_image_pull_policy: "{{ moodle_image_pull_policy }}"
nginx_container: "moodle-nginx"
nginx_startup_probe: true
nginx_startup_initial: 0
nginx_startup_command: "['{{ moodle_nginx_check_container_script }}', '-s']"
nginx_readiness_probe: true
nginx_readiness_command: "['{{ moodle_nginx_check_container_script }}', '-r']"
nginx_liveness_probe: true
nginx_liveness_command: "['{{ moodle_nginx_check_container_script }}', '-l']"
nginx_connects_to:
  - "{{ php_fpm_appname }}"
  - "{{ moodle_nfs_appname }}"
## nginx extra conf
# nginx_extra_config: ''

# ingress
nginx_ingress_host: "{{ moodle_host }}"
nginx_ingress_protocol: "{{ moodle_protocol }}"

# deploy
nginx_envvars: "{{ moodle_nginx_envvars_base + moodle_nginx_envvars_extra }}"
nginx_volumes: "{{ moodle_nginx_volumes_base + moodle_nginx_volumes_extra }}"

# nginx netpol
nginx_netpol_omit: "{{ moodle_netpol_omit }}"
nginx_netpol_ingress_ipblock: "{{ moodle_netpol_ingress_ipblock }}"
nginx_netpol_egress_ipblock: "{{ moodle_netpol_egress_ipblock }}"
