# THIS FILES IS SHARED BETWEEN MOODLE.M4E AND PHPFPM.M4E CRD

# moodle php-fpm envvars
moodle_php_fpm_database_check_socket:
  name: DATABASE_CHECK_SOCKET
  value: "{{ moodle_config_dbhost }}:{{ moodle_config_dbport | default('5432') }}"
moodle_php_fpm_envvar_data:
  name: MOODLE_DATA
  value: "{{ moodle_pvc_data_path }}"
moodle_php_fpm_envvar_data_readable:
  name: MOODLE_DATA_READABLE_DIR
  value: "'{{ 'true' if k8s_distribution == 'k8s' else 'false' }}'"
moodle_php_fpm_envvar_config:
  name: MOODLE_CONFIG_DIR
  value: "{{ moodle_config_path }}"
moodle_php_fpm_envvar_redis:
  name: REDIS_PASSWORD
  source: |-
    secretKeyRef:
      name: "{{ moodle_redis_secret }}"
      key: "{{ moodle_redis_secret_auth_key }}"
moodle_php_fpm_envvars_base: "{{ [moodle_php_fpm_database_check_socket] + [moodle_php_fpm_envvar_data] +
  [moodle_php_fpm_envvar_data_readable] + [moodle_php_fpm_envvar_config] +
  ([moodle_php_fpm_envvar_redis] if moodle_redis_secret else []) }}"
moodle_php_fpm_envvars_extra: []

# moodle php-fpm volumes
moodle_php_fpm_volume_config:
  name: config-php
  mount_path: "{{ moodle_config_path }}/config.php"
  sub_path: config.php
  read_only: true
  source: |-
    secret:
      secretName: "{{ moodle_secret_config }}"
      items:
      - key: config.php
        path: config.php
      - key: "{{ moodle_muc_config_json_file | basename }}"
        path: "{{ moodle_muc_config_json_file | basename }}"
moodle_php_fpm_volume_muc_config:
  name: config-php
  mount_path: "{{ moodle_muc_config_json_file }}"
  sub_path: "{{ moodle_muc_config_json_file | basename }}"
  read_only: true
moodle_php_fpm_volume_localcache:
  name: localcache
  mount_path: "{{ moodle_local_dir }}"
  source: |-
    emptyDir: {}
moodle_php_fpm_volume_moodledata: "{{ moodle_volume_moodledata }}"
moodle_php_fpm_volume_scripts:
  name: scripts
  mount_path: "{{ moodle_scripts_path }}"
  source: |-
    configMap:
      name: "{{ moodle_cm_scripts }}"
      defaultMode: 0555
moodle_php_fpm_volumes_base: "{{ [moodle_php_fpm_volume_config] +
  [moodle_php_fpm_volume_muc_config] + [moodle_php_fpm_volume_moodledata] +
  [moodle_php_fpm_volume_localcache] + [moodle_php_fpm_volume_scripts] }}"
moodle_php_fpm_volumes_extra: []

# php-fpm
php_fpm_appname: "{{ meta_name }}-php-fpm"
php_fpm_cm: "{{ php_fpm_appname }}-cm"
php_fpm_inventory_uuid: "{{ (cr_group + cr_version + cr_kind + meta_namespace + meta_name) | to_uuid }}"

# php-fpm deploy
# php_fpm_size: 1
php_fpm_image: "{{ moodle_image }}"
php_fpm_image_pull_policy: "{{ moodle_image_pull_policy }}"
php_fpm_container: "moodle-php-fpm"
php_fpm_port: 9000
php_fpm_startup_probe: true
php_fpm_startup_initial: 0
php_fpm_startup_period: 10
php_fpm_startup_failure: 30
php_fpm_startup_command: "{{ moodle_startup_command }}"
php_fpm_readiness_probe: true
php_fpm_readiness_command: "{{ moodle_readiness_command }}"
php_fpm_liveness_probe: true
php_fpm_liveness_command: "{{ moodle_liveness_command }}"
php_fpm_connects_to:
  - "{{ moodle_postgres_appname }}"
  - "{{ moodle_pgbouncer_appname }}"
  - "{{ moodle_keydb_appname }}"
  - "{{ moodle_nfs_appname }}"
## php.ini extra ini config
# php_fpm_php_extra_ini: ''
## php-fpm extra conf
# php_fpm_extra_config: ''

# deploy
php_fpm_envvars: "{{ moodle_php_fpm_envvars_base + moodle_php_fpm_envvars_extra }}"
php_fpm_volumes: "{{ moodle_php_fpm_volumes_base + moodle_php_fpm_volumes_extra }}"

# php-fpm config
php_fpm_config_process_control_timeout: 20

# php-fpm netpol
php_fpm_netpol_omit: "{{ moodle_netpol_omit }}"
php_fpm_netpol_ingress_ipblock: "{{ moodle_netpol_ingress_ipblock }}"
php_fpm_netpol_egress_ipblock: "{{ moodle_netpol_egress_ipblock }}"
