- name: nginx resource definitions
  vars:
    name: nginx
    k8s_state: "{{ nginx_state }}"
    component: nginx
    metadata_app: "{{ nginx_appname }}"
  block:
    # remove ingress to release any external ip
    - import_tasks: "resource/{{ nginx_ingress_type }}.yml"

    # remove deploy
    - import_tasks: resource/deploy.yml
