- name: php-fpm resource definitions
  vars:
    name: php-fpm
    k8s_state: "{{ php_fpm_state }}"
    component: php-fpm
    metadata_app: "{{ php_fpm_appname }}"
  block:
    # remove deploy
    - import_tasks: resource/deploy.yml
