- name: assert k8s api-resources is not empty
  tags: skip_ansible_lint
  ignore_errors: true
  assert:
    that: k8s_api_resources | length > 0
    fail_msg: "'k8s api-resources' is returning empty, default distribution will be: k8s_distribution"
    quiet: true

- name: assert k8s api-resources is not failed
  tags: skip_ansible_lint
  ignore_errors: true
  vars:
    _assert_k8s_api_resource_exit_code:
      "{{ k8s_api_resources | map('regex_search','^api_resources_exit_code.*') | select('string') | list }}"
  assert:
    that: not _assert_k8s_api_resource_exit_code | length > 0
    fail_msg: "'k8s api-resources' is failing, {{ _assert_k8s_api_resource_exit_code | first | default('') }}"
    quiet: true

- name: assert cr name max length
  assert:
    that: meta_name | length <= meta_name_max_length
    fail_msg: "'{{ meta_name }}' above max length for this '{{ cr_kind }}'"
    quiet: true
