- name: moodle resource definitions
  vars:
    name: moodle
    k8s_state: "{{ moodle_state }}"
    component: "{{ moodle_component | default('moodle') }}"
    metadata_app: "{{ moodle_metadata_app | default(moodle_appname) }}"
  block:
    - import_tasks: moodle/resource/moodledata-pvc.yml

    - import_tasks: moodle/resource/config-secret.yml

    - import_tasks: moodle/resource/new-instance-job.yml

    - import_tasks: moodle/resource/cronjob.yml
