---
- name: nginx resource definitions
  vars:
    name: nginx
    k8s_state: "{{ nginx_state }}"
    component: nginx
    metadata_app: "{{ nginx_appname }}"
  block:
    - import_tasks: nginx/resource/deploy.yml

    - import_tasks: nginx/resource/service.yml

    - import_tasks: nginx/resource/route.yml

    - import_tasks: nginx/resource/ingress.yml
