- name: postgres resource definitions
  vars:
    name: postgres
    k8s_state: "{{ postgres_state }}"
    component: postgres
    metadata_app: "{{ postgres_appname }}"
  block:
    - import_tasks: postgres/resource/pvc.yml

    - import_tasks: postgres/resource/secret.yml

    - import_tasks: postgres/resource/deploy.yml

    - import_tasks: postgres/resource/service.yml
