- name: nfs resource definitions
  vars:
    name: nfs
    k8s_state: "{{ server_state }}"
    component: nfs
    metadata_app: "{{ server_appname }}"
  block:
    - import_tasks: nfs/resources/sc.yml
    
    - import_tasks: nfs/resources/server.yml

    - import_tasks: nfs/resources/pvc.yml
