- name: moodle php-fpm resource definition
  vars:
    k8s_kind: Phpfpm
    k8s_state: "{{ moodle_php_fpm_state | default(moodle_state) }}"
    template: "{{ php_fpm_template }}"
    metadata_name: "{{ moodle_php_fpm }}"
    annotations: "{{ moodle_php_fpm_annotations | default(false) }}"
    php_fpm_spec: "{{ moodle_php_fpm_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save moodle php-fpm resource definition task
  set_fact:
    k8s_moodle_php_fpm: "{{ k8s_object_task }}"

- name: wait for moodle php-fpm resource
  vars:
    wait_resource_conditions: "{{ k8s_moodle_php_fpm.result.status.conditions | default([]) }}"
    wait_resource_kind: Phpfpm
    wait_resource_name: "{{ moodle_php_fpm }}"
  when:
    - not ansible_check_mode
    - k8s_moodle_php_fpm is defined
    - moodle_php_fpm_state | default(moodle_state) != 'absent'
    - moodle_php_fpm_wait | default(_moodle_k8s_wait) | default(true)
  include_tasks: "{{ common_path }}/wait/resource.yml"
