- name: (nfs) ganesha server resource definitions
  vars:
    name: nfs-ganesha
    k8s_state: "{{ ganesha_state }}"
    component: nfs
    metadata_app: "{{ ganesha_appname }}"
  block:
    # remove routine for avoiding state modifications
    - import_tasks: resource/routine.yml

    # remove ganesha server sts
    - import_tasks: resource/sts.yml

    # ensure generated storage class is removed
    - import_tasks: resource/sc-generated.yml
      when: ganesha_generated_nfs_sc_needed

    # remove any remaining pvc
    - import_tasks: "{{ common_path }}/cleanup-resources.yml"
      vars:
        cleanup_label_selector: "app={{ metadata_app }}"
        cleanup_kind_list:
          - PersistentVolumeClaim
