- name: import tasks
  block:
    - name: make assertions
      import_tasks: "{{ role_path }}/tasks/assertions.yml"

    - name: handle resources depending on postgres mode
      import_tasks: "{{ role_path }}/tasks/state/present/{{ postgres_mode }}.yml"

    - name: include successful status
      import_tasks: "{{ role_path }}/tasks/condition/ready/successful.yml"
  rescue:
    - name: include rescue tasks
      import_tasks: "{{ common_path }}/rescue.yml"
