- name: get mount info
  register: mount_info_task
  mount_info:
    path: "/{{ server_pvc }}"

- name: status
  when:
    - mount_info_task is defined
    - mount_info_task.mount_info is defined and mount_info_task.mount_info
  delegate_to: localhost
  block:
    - name: set mount info in nfs status
      import_tasks: "{{ common_path }}/k8s/status.yml"
      vars:
        k8s_status_properties:
          usage:
            - description: Storage available
              name: size_available
              unit: GiB
              value: "{{ mount_info_task.mount_info.size_available | krestomatio.k8s.b_to_gib }}"
            - description: Total storage
              name: size_total
              unit: GiB
              value: "{{ mount_info_task.mount_info.size_total | krestomatio.k8s.b_to_gib }}"

    - name: set expansion required status
      import_tasks: "condition/expanded/{{ 'required' if mount_info_task.mount_info.size_available |
        default(0) < mount_info_task.mount_info.size_total | default(0) * 0.2 else 'not-required' }}.yml"
