- name: postgres read only service resource definition
  vars:
    k8s_kind: Service
    k8s_state:
      "{{ 'absent' if postgres_mode not in ['readreplicas'] else
      postgres_readonly_service_state | default(postgres_state) }}"
    template: "{{ service_template }}"
    metadata_name: "{{ postgres_readonly_service }}"
    service_spec: "{{ postgres_readonly_service_spec }}"
  include_tasks: "{{ common_path }}/k8s/object.yml"

- name: save postgres read only service resource definition task
  set_fact:
    k8s_postgres_readonly_service: "{{ k8s_object_task }}"
