- name: routine to enforce redis muc store config
  when: routine_redis_muc_config | bool
  run_once: true
  register: routine_redis_muc_config_task
  command: "{{ routine_redis_muc_config_script if
    routine_redis_muc_config_script is search(' -o ') else
    routine_redis_muc_config_script + ' -o ' }}"
