---
# php-fpm
php_fpm_state: "{{ state }}"
php_fpm_appname: "{{ meta_name }}-php-fpm"

# php-fpm deploy
php_fpm_size: 1
php_fpm_image: quay.io/krestomatio/php-fpm@sha256:f8c03f70b0c15a27be37e0a71c4dc7d186a8053f613e7f44e67263cbf297212e
php_fpm_image_pull_secret: "{{ image_pull_secret }}"
php_fpm_deploy: "{{ php_fpm_appname }}-deploy"
php_fpm_port: 9000
php_fpm_args: "['php-fpm']"
php_fpm_container: "php-fpm"
php_fpm_container_group: "{{ php_fpm_container.replace('-', '_') }}"
php_fpm_startup_probe: false
php_fpm_startup_command: "['{{ php_fpm_check_container_script }}', '-s']"
php_fpm_startup_initial: 5
php_fpm_startup_period: 10
php_fpm_startup_timeout: 3
php_fpm_startup_success: 1
php_fpm_startup_failure: 6
php_fpm_readiness_probe: false
php_fpm_readiness_command: "['{{ php_fpm_check_container_script }}', '-r']"
php_fpm_readiness_initial: 5
php_fpm_readiness_period: 10
php_fpm_readiness_timeout: 3
php_fpm_readiness_success: 1
php_fpm_readiness_failure: 6
php_fpm_liveness_probe: false
php_fpm_liveness_command: "['{{ php_fpm_check_container_script }}', '-l']"
php_fpm_liveness_initial: 5
php_fpm_liveness_period: 10
php_fpm_liveness_timeout: 3
php_fpm_liveness_success: 1
php_fpm_liveness_failure: 3
php_fpm_check_container_script: /usr/libexec/check-container-php
php_fpm_resource_requests: true
php_fpm_resource_requests_cpu: 15m
php_fpm_resource_requests_memory: 32Mi
php_fpm_resource_limits: false
php_fpm_resource_limits_cpu: 1
php_fpm_resource_limits_memory: 1Gi
php_fpm_term_grace_period: 30
php_fpm_tolerations: false
php_fpm_node_selector: false
php_fpm_affinity: false
php_fpm_connects_to: false
# php_fpm_envvars:
#   - name: NGINX_FASTCGI_PASS
#     value: php-service:9000
# php_fpm_volumes:
#   - name: html
#     mount_path: /var/www/html
#     source: |-
#       persistentVolumeClaim:
#         claimName: metadata-pvc

# php-fpm config map
php_fpm_cm: "{{ php_fpm_appname }}-cm"
php_fpm_cm_data: |
  php-extra.ini: |
    {{ php_fpm_php_extra_ini | indent(2) }}
  php-fpm-extra.conf: |
    {{ php_fpm_extra_config | indent(2) }}
## php.ini extra ini config
php_fpm_php_extra_ini: ''
## php-fpm extra conf
php_fpm_extra_config: ''

# php-fpm service
php_fpm_service: "{{ php_fpm_appname }}-service"
php_fpm_service_type: ClusterIP
php_fpm_service_spec: |
  type: {{ php_fpm_service_type }}
  sessionAffinity: {{ php_fpm_service_session_affinity | default('None') }}
  {% if php_fpm_service_session_affinity_timeout is defined %}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ php_fpm_service_session_affinity_timeout }}
  {% endif %}
  ports:
  - name: http
    port: {{ php_fpm_port }}
    protocol: TCP
    targetPort: {{ php_fpm_port }}
  selector:
    app: '{{ php_fpm_appname }}'

# php-fpm hpa
php_fpm_hpa: "{{ php_fpm_appname }}-hpa"
php_fpm_hpa_spec: false

# php-fpm vpa
php_fpm_vpa: "{{ php_fpm_appname }}-vpa"
php_fpm_vpa_spec: false

# php-fpm netpol
php_fpm_netpol_omit: true
php_fpm_netpol: "{{ php_fpm_appname }}-netpol"
php_fpm_netpol_ingress_ipblock: false
php_fpm_netpol_egress_ipblock: false
php_fpm_netpol_connects_to: "{{ php_fpm_connects_to if php_fpm_connects_to | type_debug == 'list' else [php_fpm_connects_to | default('')] }}"
php_fpm_netpol_spec: |-
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/runtime: 'php-fpm'
  ingress:
  {% if php_fpm_netpol_ingress_extra_ports | default([]) %}
  - ports:
  {% for _extra_port in php_fpm_netpol_ingress_extra_ports %}
    - protocol: "{{ _extra_port.protocol | default('TCP') }}"
      port: {{ _extra_port.port }}
  {% endfor %}
  {% endif %}
  - from:
    - podSelector:
        matchLabels:
          {{ meta_app_connects_to }}/{{ php_fpm_appname }}: 'true'
  {% if php_fpm_netpol_ingress_ipblock is defined and php_fpm_netpol_ingress_ipblock %}
    - ipBlock:
        cidr: '{{ php_fpm_netpol_ingress_ipblock }}'
  {% endif %}
  egress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 465
    - protocol: TCP
      port: 587
    - protocol: TCP
      port: 636
  {% for _extra_port in php_fpm_netpol_egress_extra_ports | default([]) %}
    - protocol: "{{ _extra_port.protocol | default('TCP') }}"
      port: {{ _extra_port.port }}
  {% endfor %}
  {% for php_fpm_netpol_connects_to_app_name in php_fpm_netpol_connects_to if php_fpm_netpol_connects_to_app_name %}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ php_fpm_netpol_connects_to_app_name }}'
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ php_fpm_netpol_connects_to_app_name }}'
      podSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ php_fpm_netpol_connects_to_app_name }}'
  {% endfor %}
  {% if php_fpm_netpol_egress_ipblock is defined and php_fpm_netpol_egress_ipblock %}
    - ipBlock:
        cidr: '{{ php_fpm_netpol_egress_ipblock }}'
  {% endif %}
