- name: postgres pvc resource definition
  vars:
    k8s_kind: PersistentVolumeClaim
    k8s_state: "{{ postgres_pvc_state | default(postgres_state) }}"
    template: "{{ pvc_template }}"
    metadata_name: "{{ postgres_pvc }}"
    pvc_spec: "{{ postgres_pvc_spec }}"
  import_tasks: "{{ common_path }}/k8s/object.yml"

- name: save postgres pvc resource definition task
  set_fact:
    k8s_postgres_pvc: "{{ k8s_object_task }}"
