- name: moodle cronjob
  vars:
    moodle_component: "cronjob"
  block:
    - name: set moodle cronjob spec
      when: moodle_cronjob_spec is not defined
      vars:
        annotations: "{{ moodle_cronjob_spec_annotations | default(false) }}"
        extra_labels: "{{ moodle_cronjob_spec_extra_labels | default(false) }}"
      set_fact:
        moodle_cronjob_spec: "{{ lookup('template', moodle_cronjob_spec_template) }}"

    - name: moodle cronjob resource definition
      vars:
        k8s_kind: CronJob
        k8s_state: "{{ moodle_cronjob_state | default(moodle_state) }}"
        template: "{{ cronjob_template }}"
        metadata_name: "{{ moodle_cronjob }}"
        cronjob_spec: "{{ moodle_cronjob_spec }}"
      import_tasks: "{{ common_path }}/k8s/object.yml"

    - name: save moodle cronjob resource definition task
      set_fact:
        k8s_moodle_cronjob: "{{ k8s_object_task }}"
