- name: moodle new instance
  when: not (cr_status_properties.instantiated | default('False') | bool)
  vars:
    moodle_component: "job"
  block:
    - name: include not instantiated status
      import_tasks: condition/instantiated/not-instantiated.yml

    - name: set moodle new instance job spec
      when: moodle_new_instance_job_spec is not defined
      vars:
        metadata_name: "{{ moodle_new_instance_job }}"
        annotations: "{{ moodle_new_instance_job_annotations | default(false) }}"
        extra_labels: "{{ moodle_new_instance_job_extra_labels | default(false) }}"
      set_fact:
        moodle_new_instance_job_spec:
          "{{ lookup('template', moodle_new_instance_job_spec_template) }}"

    - name: moodle new instance job resource definition
      vars:
        k8s_kind: Job
        k8s_state: "{{ moodle_new_instance_job_state | default(moodle_state) }}"
        k8s_wait: true
        k8s_wait_timeout: "{{ moodle_new_instance_wait_timeout }}"
        k8s_wait_condition:
          type: "Complete"
          status: "True"
        template: "{{ job_template }}"
        metadata_name: "{{ moodle_new_instance_job }}"
        job_spec: "{{ moodle_new_instance_job_spec }}"
      import_tasks: "{{ common_path }}/k8s/object.yml"

    - name: save moodle new instance job resource definition task
      set_fact:
        k8s_moodle_new_instance_job: "{{ k8s_object_task }}"

    - name: include instantiated status
      import_tasks: condition/instantiated/instantiated.yml
