apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: release
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            env:
              - name: HOME
                value: /tekton/home
              - name: VERSION_MAKEFILE
                value: "true"
              - name: PROJECT_TIMESTAMP
                value: midnight
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@e3ba7ae6c62bc3ee26c073920d5662556a21f51f
            - image: ghcr.io/jenkins-x/jx-changelog:0.0.47
              name: changelog
              args:
              - changelog
              command:
              - make
            - image: quay.io/krestomatio/ansible-docker-ci
              name: release
              env:
                - name: ANSIBLE_GALAXY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ansible-galaxy-api-key
                      key: apikey
              args:
              - release
              command:
              - make
            - name: promote
              image: ghcr.io/jenkins-x/jx-updatebot:0.0.86
              args:
              - promote
              command:
              - make
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
