apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        persistentVolumeReclaimPolicy: Delete
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
    - name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace
      taskRef:
        name: git-clone
      params:
      - name: VERSION_MAKEFILE
        value: "true"
      - name: PROJECT_TIMESTAMP
        value: midnight
    - name: release
      resources: {}
      runAfter:
      - git-clone
      workspaces:
      - name: source
        workspace: shared-workspace
      taskSpec:
        metadata: {}
        workspaces:
        - name: source
          mountPath: /workspace
        stepTemplate:
          name: ''
          env:
          - name: HOME
            value: /workspace
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 32Mi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-changelog:0.0.47
          name: changelog
          args:
          - changelog
          command:
          - make
        - image: quay.io/krestomatio/ansible-docker-ci
          name: release
          env:
          - name: ANSIBLE_GALAXY_TOKEN
            valueFrom:
              secretKeyRef:
                name: ansible-galaxy-api-key
                key: apikey
          args:
          - "600"
          command:
          - sleep
          resources:
            limits:
              cpu: 750
              memory: 2048Mi
            requests:
              cpu: 0.1
              memory: 128Mi
        - name: promote
          image: ghcr.io/jenkins-x/jx-updatebot:0.0.86
          args:
          - promote
          command:
          - make
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
