---
# defaults file for m4e
cr_group: m4e.krestomat.io
cr_kind: M4e

# custom resource state: present, absent, suspended, inmaintenance
cr_state: present

# expose
expose_type: "ingress"  # only route
expose_tls: false
expose_tls_secret_name: false

# url
host: "m4e"
domain: "krestomat.io"
fqdn: "{{ host }}.{{ domain }}"

# credentials. MUST CHANGED
database_name: moodle
database_user: user
database_password: secret

# templates
moodle_config_template: moodle/config.php.j2
postgres_deploy_spec_template: deploy/postgres-spec.yaml.j2
php_fpm_deploy_spec_template: deploy/php-fpm-spec.yaml.j2
nginx_deploy_spec_template: deploy/nginx-spec.yaml.j2
moodle_new_instance_job_spec_template: job/moodle-new-instance-spec.yaml.j2
moodle_cronjob_spec_template: cronjob/moodle-spec.yaml.j2

# common labels
meta_app_part_of: moodle
meta_app_created_by: m4e-operator
