---
# nginx
nginx_size: 1
nginx_image: quay.io/krestomatio/moodle_web
nginx_state: "{{ state }}"
nginx_appname: "{{ meta_name }}-nginx"
nginx_service: "{{ nginx_appname }}-service"
nginx_deploy: "{{ nginx_appname }}-deploy"
nginx_route: "{{ nginx_appname }}-route"
nginx_ingress: "{{ nginx_appname }}-ingress"
nginx_port: 8080
nginx_host: "{{ fqdn }}"
nginx_args: "['nginx']"
nginx_container: "moodle-nginx"
nginx_container_group: "{{ nginx_container.replace('-', '_') }}"
nginx_readiness_probe: true
nginx_readiness_path: "/login/index.php"
nginx_readiness_initial: 5
nginx_readiness_period: 30
nginx_readiness_timeout: 3
nginx_readiness_success: 1
nginx_readiness_failure: 6
nginx_liveness_probe: true
nginx_liveness_path: "/login/index.php"
nginx_liveness_initial: 5
nginx_liveness_period: 10
nginx_liveness_timeout: 3
nginx_liveness_success: 1
nginx_liveness_failure: 3
nginx_resource_requests: true
nginx_resource_requests_cpu: 75m
nginx_resource_requests_memory: 128Mi
nginx_resource_limits: false
nginx_resource_limits_cpu: 1
nginx_resource_limits_memory: 1Gi
nginx_term_grace_period: 30
nginx_run_as_user: 999
nginx_ingress_tls: "{{ expose_tls }}"
nginx_route_tls: "{{ expose_tls }}"
nginx_ingress_tls_secret_name: "{{ expose_tls_secret_name }}"
nginx_route_annotations: |
  haproxy.router.openshift.io/rate-limit-connections: 'true'
  haproxy.router.openshift.io/rate-limit-connections.concurrent-tcp: '100'
  haproxy.router.openshift.io/rate-limit-connections.rate-http: '100'
  haproxy.router.openshift.io/rate-limit-connections.rate-tcp: '100'
nginx_route_spec: |
  host: '{{ nginx_host }}'
  to:
    kind: Service
    name: '{{ nginx_service }}'
    weight: 100
  port:
    targetPort: http
  {% if nginx_route_tls %}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {% endif %}
  wildcardPolicy: None
nginx_ingress_spec: |
  {% if nginx_ingress_tls %}
  tls:
  - hosts:
    - '{{ nginx_host }}'
  {% if nginx_ingress_tls_secret_name is defined and nginx_ingress_tls_secret_name %}
    secretName: {{ nginx_ingress_tls_secret_name }}
  {% endif %}
  {% endif %}
  rules:
  - host: '{{ nginx_host }}'
    http:
      paths:
      - path: {{ nginx_ingress_path | default('/') }}
        backend:
          serviceName: '{{ nginx_service }}'
          servicePort: {{ nginx_port }}
nginx_service_type: ClusterIP
nginx_service_spec: |
  type: {{ nginx_service_type }}
  sessionAffinity: {{ nginx_service_session_affinity | default('None') }}
  {% if nginx_service_session_affinity_timeout is defined %}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ nginx_service_session_affinity_timeout }}
  {% endif %}
  ports:
  - name: http
    port: {{ nginx_port }}
    protocol: TCP
    targetPort: {{ nginx_port }}
  selector:
    app: '{{ nginx_appname }}'
nginx_tolerations: false
