---
# php-fpm
php_fpm_size: 1
php_fpm_image: quay.io/krestomatio/moodle_web
php_fpm_state: "{{ state }}"
php_fpm_appname: "{{ meta_name }}-php-fpm"
php_fpm_service: "{{ php_fpm_appname }}-service"
php_fpm_deploy: "{{ php_fpm_appname }}-deploy"
php_fpm_args: "['php-fpm']"
php_fpm_container: "moodle-php-fpm"
php_fpm_container_group: "{{ php_fpm_container.replace('-', '_') }}"
php_fpm_readiness_probe: true
php_fpm_readiness_command: "['/usr/libexec/check-container-php', '-t', '-r']"
php_fpm_readiness_initial: 5
php_fpm_readiness_period: 30
php_fpm_readiness_timeout: 3
php_fpm_readiness_success: 1
php_fpm_readiness_failure: 6
php_fpm_liveness_probe: true
php_fpm_liveness_command: "['/usr/libexec/check-container-php', '-t', '-l']"
php_fpm_liveness_initial: 5
php_fpm_liveness_period: 10
php_fpm_liveness_timeout: 3
php_fpm_liveness_success: 1
php_fpm_liveness_failure: 3
php_fpm_resource_requests: true
php_fpm_resource_requests_cpu: 150m
php_fpm_resource_requests_memory: 256Mi
php_fpm_resource_limits: false
php_fpm_resource_limits_cpu: 1
php_fpm_resource_limits_memory: 1Gi
php_fpm_term_grace_period: 30
php_fpm_service_spec: |
  type: {{ php_fpm_service_type | default('ClusterIP') }}
  sessionAffinity: {{ php_fpm_service_session_affinity | default('ClientIP')  }}
  {% if php_fpm_service_session_affinity_timeout is defined %}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ php_fpm_service_session_affinity_timeout }}
  {% endif %}
  ports:
  - name: php-fpm
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: '{{ php_fpm_appname }}'
php_fpm_tolerations: false
# php-fpm config
php_fpm_process_control_timeout: 20
