---
# postgres
## postgres size is either 1 or 0. If > 1 it will be converted to 1
postgres_size: 1
postgres_image: quay.io/krestomatio/postgres
postgres_state: "{{ state }}"
postgres_appname: "{{ meta_name }}-postgres"
postgres_pvc: "{{ postgres_appname }}-pvc"
postgres_secret: "{{ postgres_appname }}-secret"
postgres_service: "{{ postgres_appname }}-service"
postgres_deploy: "{{ postgres_appname }}-deploy"
postgres_container: "moodle-postgres"
postgres_container_group: "{{ postgres_container.replace('-', '_') }}"
postgres_readiness_probe: true
postgres_readiness_command: "['/usr/libexec/check-container-postgres']"
postgres_readiness_initial: 5
postgres_readiness_period: 10
postgres_readiness_timeout: 1
postgres_readiness_success: 1
postgres_readiness_failure: 3
postgres_liveness_probe: true
postgres_liveness_command: "['/usr/libexec/check-container-postgres', '--live']"
postgres_liveness_initial: 120
postgres_liveness_period: 10
postgres_liveness_timeout: 10
postgres_liveness_success: 1
postgres_liveness_failure: 3
postgres_resource_requests: true
postgres_resource_requests_cpu: 150m
postgres_resource_requests_memory: 256Mi
postgres_resource_limits: false
postgres_resource_limits_cpu: 1
postgres_resource_limits_memory: 1Gi
postgres_term_grace_period: 30
postgres_data: /var/lib/pgsql/data
postgres_secret_data: |
  database_password: '{{ database_password | b64encode }}'
postgres_service_spec: |
  selector:
    app: '{{ postgres_appname }}'
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  sessionAffinity: ClientIP
postgres_pvc_storage_access_modes: ReadWriteOnce
postgres_pvc_size: 1Gi
postgres_pvc_spec: |
  {% if postgres_pvc_storage_class_name is defined and postgres_pvc_storage_class_name %}
  storageClassName: {{ postgres_pvc_storage_class_name }}
  {% endif %}
  accessModes:
    - '{{ postgres_pvc_storage_access_modes }}'
  resources:
    requests:
      storage: '{{ postgres_pvc_size }}'
postgres_tolerations: false
# postgres config
postgres_log_stderr: true
